# src.nikhil.pravaha.domain.storage.protocol.storage_config_protocol.py
from typing import Protocol, Dict, Optional

class StorageConfigProtocol(Protocol):
    def update_config(self, output_path: str, intermediate_path: str, knowledge_path: str) -> None: ...
    def get_config(self) -> Dict[str, Optional[str]]: ...
    def is_configured(self) -> bool: ...