import pytest
from fastapi.testclient import TestClient
from pravaha_example.service.server import app
from pravaha_example.config.settings import ApplicationType, UtilsType
from pravaha.domain.auth.repository.json_access_key_repository import JsonAccessKeyRepository
from pravaha.domain.auth.model.module import PravahaModule

# Setup: Create a real API Key for the test
repo = JsonAccessKeyRepository()
# Create a temporary key with ALL permissions
api_key = repo.create_key(
    name="E2E_Test_Key",
    description="Generated by test_example_server.py",
    permissions=[m for m in PravahaModule]
)
# Note: In a real environment we might want to clean this up, but for E2E it's fine.

client = TestClient(app, headers={"X-API-Key": api_key.key})


# Seed Test Data using tmp_path and internal API config
from pathlib import Path
import json

@pytest.fixture(scope="module")
def storage_setup(tmp_path_factory):
    """
    Setup temporary storage directory and configure the server to use it.
    Using module scope requires tmp_path_factory.
    """
    # Create temp dir
    temp_root = tmp_path_factory.mktemp("test_storage")
    output_path = temp_root / "output"
    inter_path = temp_root / "intermediate"
    know_path = temp_root / "knowledge"
    
    output_path.mkdir()
    inter_path.mkdir()
    know_path.mkdir()
    
    # Configure Server via API
    # We need to do this BEFORE running storage tests.
    config_payload = {
        "output_path": str(output_path),
        "intermediate_path": str(inter_path),
        "knowledge_path": str(know_path)
    }
    resp = client.post("/api/storage/config", json=config_payload)
    assert resp.status_code == 200, f"Config failed: {resp.text}"

    # Seed Data
    # Output - valid hierarchy for Browse [Product/Feature/File]
    (output_path / "TestProduct" / "TestFeature").mkdir(parents=True, exist_ok=True)
    with open(output_path / "TestProduct" / "TestFeature" / "result.json", "w") as f:
        json.dump({"status": "nested"}, f)
    
    # Root file (may not show in browse if strict hierarchy but readable)
    with open(output_path / "root_result.json", "w") as f:
        json.dump({"status": "root"}, f)

    # Intermediate
    with open(inter_path / "step1.json", "w") as f:
        json.dump({"step": 1}, f)
        
    (inter_path / "nested_inter").mkdir(parents=True, exist_ok=True)
    with open(inter_path / "nested_inter" / "temp.json", "w") as f:
        json.dump({"step": 2}, f)

    # Knowledge
    with open(know_path / "root_info.md", "w") as f:
        f.write("# Root Info\nContent")
    
    (know_path / "nested_wiki").mkdir(parents=True, exist_ok=True)
    with open(know_path / "nested_wiki" / "python.md", "w") as f:
        f.write("# Python\nContent")
        
    return temp_root

def test_run_calculator_utility(storage_setup):
    # Test valid addition
    payload = {
        "task_name": UtilsType.CALCULATOR.value,
        "inputs": [{"operation": "add", "a": 5, "b": 3}]
    }
    response = client.post("/api/run/utility", json=payload)
    assert response.status_code == 200
    assert response.json() == {"status": "success", "result": 8}
    
    # Test valid multiplication
    payload["inputs"] = [{"operation": "multiply", "a": 5, "b": 3}]
    response = client.post("/api/run/utility", json=payload)
    assert response.status_code == 200
    assert response.json()["result"] == 15

def test_run_calculator_invalid_operation():
    payload = {
        "task_name": UtilsType.CALCULATOR.value,
        "inputs": [{"operation": "divide", "a": 5, "b": 3}]
    }
    response = client.post("/api/run/utility", json=payload)
    assert response.status_code == 200
    assert "Unknown operation" in response.json()["result"]

def test_run_app_math_bot_stream():
    payload = {
        "task_name": ApplicationType.MATH_ASSISTANT.value,
        "inputs": [{"question": "1+1"}]
    }
    response = client.post("/api/run/application/stream", json=payload)
    assert response.status_code == 200
    
    # Check headers (Starlette SSE sets these)
    assert response.headers["content-type"] == "text/event-stream; charset=utf-8"
    
    # Check content
    content = response.text
    assert "Hello! I am the Math Assistant." in content
    assert "Processing: {'question': '1+1'}" in content
    assert "[DONE]" in content

def test_run_app_math_bot_stream_no_inputs():
    payload = {
        "task_name": ApplicationType.MATH_ASSISTANT.value
        # No inputs provided
    }
    response = client.post("/api/run/application/stream", json=payload)
    assert response.status_code == 200
    
    content = response.text
    assert "Hello! I am the Math Assistant." in content
    # Should NOT process any inputs implies "Processing:" might not appear or logic handles it?
    # MathBot: if inputs: ...
    assert "Processing:" not in content
    assert "[DONE]" in content


def test_storage_list_output_folders(storage_setup):
    # Browse endpoint returns List depending on provider.
    response = client.get("/api/storage/output/browse")
    assert response.status_code == 200
    data = response.json()
    assert isinstance(data, list)

def test_storage_browse_output(storage_setup):
    response = client.get("/api/storage/output/browse")
    assert response.status_code == 200
    data = response.json()
    assert isinstance(data, list)
    
    # We seeded output/TestProduct/TestFeature/result.json
    # OutputStorageProvider browse should find it and return Grouped Artifacts.
    if len(data) > 0:
        found = False
        for item in data:
            if item.get("product") == "TestProduct" and item.get("feature") == "TestFeature":
                found = True
                break
        assert found, f"Did not find TestProduct/TestFeature in {data}"

def test_storage_comprehensive_scenarios(storage_setup):
    # 1. Output (JSON content)
    # Root file
    resp = client.get("/api/storage/output/read?path=root_result.json")
    assert resp.status_code == 200
    assert resp.json()["content"]["status"] == "root"
    
    # Nested file (Valid Hierarchy)
    resp = client.get("/api/storage/output/read?path=TestProduct/TestFeature/result.json")
    assert resp.status_code == 200
    assert resp.json()["content"]["status"] == "nested"

    # 2. Intermediate (JSON content)
    # Root file
    resp = client.get("/api/storage/intermediate/read?path=step1.json")
    assert resp.status_code == 200
    assert resp.json()["content"]["step"] == 1
    
    # Nested file
    resp = client.get("/api/storage/intermediate/read?path=nested_inter/temp.json")
    assert resp.status_code == 200
    assert resp.json()["content"]["step"] == 2

    # 3. Knowledge (Markdown content)
    # Root file
    resp = client.get("/api/storage/knowledge/read?path=root_info.md")
    assert resp.status_code == 200
    assert "# Root Info" in resp.json()["content"]
    
    # Nested file
    resp = client.get("/api/storage/knowledge/read?path=nested_wiki/python.md")
    assert resp.status_code == 200
    assert "# Python" in resp.json()["content"]
    
    # 4. Verify Browsing Knowledge
    resp = client.get("/api/storage/knowledge/browse?path=nested_wiki")
    assert resp.status_code == 200
    data = resp.json()
    # Knowledge browse usually returns list of FileItem or similar
    if isinstance(data, dict) and "items" in data:
         items = data["items"]
         assert any(i["name"] == "python.md" for i in items)
    elif isinstance(data, list):
         # Standard File Browser returns list of dicts
         assert any(i["name"] == "python.md" for i in data)
