from typing import Protocol, List, Optional, Dict, Any
from ..entity.workflow_run import WorkflowRun
from ..entity.run_state import RunState

class RunRepositoryProtocol(Protocol):
    def save(self, run: WorkflowRun) -> None: ...
    def get(self, run_id: str) -> Optional[WorkflowRun]: ...
    def update_node_state(self, run_id: str, node_id: str, state: RunState) -> None: ...
    def list_by_workflow(self, workflow_id: str) -> List[WorkflowRun]: ...
    def list_all(self) -> List[WorkflowRun]: ...
    
    # Node output storage for client-driven execution
    def save_node_output(self, run_id: str, node_id: str, output: Dict[str, Any]) -> None: ...
    def get_node_output(self, run_id: str, node_id: str) -> Optional[Dict[str, Any]]: ...
