# src.nikhil.pravaha.domain.workflow.protocol.workflow_config_protocol.py
from typing import Protocol, Dict, Optional

class WorkflowConfigProtocol(Protocol):
    def update_config(self, details_path: str, run_path: str) -> None: ...
    def get_config(self) -> Dict[str, Optional[str]]: ...
    def is_configured(self) -> bool: ...
